# frozen_string_literal: true

FactoryBot.define do
  factory :form27_2008_submission, class: 'Form27_2008Submission' do
    form_data do
      {
        'applicantType'        => 'nextOfKin',
        'dateSigned'           => '2024-01-15',
        'certificationChecked' => true,
        'veteranInformation' => {
          'firstName'                => 'John',
          'middleName'               => 'Q',
          'lastName'                 => 'Veteran',
          'dateOfBirth'              => '1945-06-15',
          'dateOfDeath'              => '2024-01-10',
          'dateOfBurial'             => '2024-01-17',
          'placeOfBurialCemeteryName' => 'Arlington National Cemetery',
          'placeOfBurialCity'        => 'Arlington',
          'placeOfBurialState'       => 'VA'
        },
        'serviceInformation' => {
          'branchOfService'            => ['army'],
          'dateEnteredActiveDuty'      => '1965-03-01',
          'dateReleasedFromActiveDuty' => '1968-02-28'
        },
        'eligibility' => {
          'documentationAvailable' => true,
          'dischargeCharacter'     => 'honorable'
        },
        'flagRecipient' => {
          'recipientFullName'     => 'Jane Veteran',
          'recipientRelationship' => 'survivingSpouse',
          'recipientAddressLine1' => '123 Main St',
          'recipientCity'         => 'Springfield',
          'recipientState'        => 'VA',
          'recipientZip'          => '22001'
        },
        'applicant' => {
          'firstName'             => 'Jane',
          'lastName'              => 'Veteran',
          'addressLine1'          => '123 Main St',
          'city'                  => 'Springfield',
          'state'                 => 'VA',
          'zip'                   => '22001',
          'relationshipToVeteran' => 'survivingSpouse'
        },
        'documents' => { 'dd214Upload' => [] },
        'metadata'  => {}
      }
    end

    user_uuid         { nil }
    confirmation_number { nil } # auto-generated by before_create callback
    submitted_at      { nil }

    trait :submitted do
      submitted_at      { 1.hour.ago }
      confirmation_number { "BF-#{Time.current.strftime('%Y%m%d')}-#{SecureRandom.hex(4).upcase}" }
    end

    trait :with_user do
      user_uuid { SecureRandom.uuid }
    end

    trait :with_document_uploads do
      form_data do
        {
          'applicantType'        => 'nextOfKin',
          'dateSigned'           => '2024-01-15',
          'certificationChecked' => true,
          'veteranInformation' => {
            'firstName'                => 'John',
            'lastName'                 => 'Veteran',
            'dateOfBirth'              => '1945-06-15',
            'dateOfDeath'              => '2024-01-10',
            'dateOfBurial'             => '2024-01-17',
            'placeOfBurialCemeteryName' => 'Arlington National Cemetery',
            'placeOfBurialCity'        => 'Arlington',
            'placeOfBurialState'       => 'VA'
          },
          'serviceInformation' => {
            'branchOfService'            => ['army'],
            'dateEnteredActiveDuty'      => '1965-03-01',
            'dateReleasedFromActiveDuty' => '1968-02-28'
          },
          'eligibility' => {
            'documentationAvailable' => true,
            'dischargeCharacter'     => 'honorable'
          },
          'flagRecipient' => {
            'recipientFullName'     => 'Jane Veteran',
            'recipientRelationship' => 'survivingSpouse',
            'recipientAddressLine1' => '123 Main St',
            'recipientCity'         => 'Springfield',
            'recipientState'        => 'VA',
            'recipientZip'          => '22001'
          },
          'applicant' => {
            'firstName'             => 'Jane',
            'lastName'              => 'Veteran',
            'addressLine1'          => '123 Main St',
            'city'                  => 'Springfield',
            'state'                 => 'VA',
            'zip'                   => '22001',
            'relationshipToVeteran' => 'survivingSpouse'
          },
          'documents' => {
            'dd214Upload' => [
              {
                'name'            => 'DD214_John_Veteran.pdf',
                'guid'            => SecureRandom.uuid,
                'confirmationCode' => SecureRandom.hex(8),
                'uploadedAt'      => 2.hours.ago.iso8601
              }
            ]
          },
          'metadata' => {}
        }
      end
    end

    trait :ineligibility_flagged do
      form_data do
        base = attributes_for(:form27_2008_submission)[:form_data]
        base.deep_merge(
          'eligibility' => { 'dischargeCharacter' => 'dishonorable' },
          'metadata'    => { 'ineligibilityFlagged' => true }
        )
      end
    end
  end
end